apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocr-model-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ocr-project
  source:
    repoURL: 'https://github.com/azmeth23/devops-assignment.git'
    targetRevision: HEAD
    path: charts/ocr-model-server
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ocr-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocr-api-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ocr-project
  source:
    repoURL: 'https://github.com/azmeth23/devops-assignment.git'
    targetRevision: HEAD
    path: charts/api-gateway
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ocr-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true