alertmanager:
  enabled: false

grafana:
  enabled: true
  service:
    type: NodePort
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  adminPassword: "admin" 

prometheus:
  prometheusSpec:
    retention: 1d
    storageSpec: {}
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

#Agent placed on a node for stats
nodeExporter:
  enabled: true
kubeStateMetrics:
  enabled: true